[package]
name = "mun_capi_utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
insta = { version ="1.12.0", features=["ron"], optional=true}
