variables:
  RUSTFLAGS: -Dwarnings

jobs:
  # Check formatting
  - template: ci/azure-rustfmt.yml
    parameters:
      rust: stable
      name: rustfmt

  - template: ci/azure-cargo-check.yml
    parameters:
      rust: stable
      name: check 