[package]
name = "mun_language_server"
version = "0.1.0"
authors = ["The Mun Team <team@mun-lang.org>"]
edition = "2018"
description = "Provides a language server protocol server for the Mun language"
documentation = "https://docs.mun-lang.org/v0.2"
readme = "README.md"
homepage = "https://mun-lang.org"
repository = "https://github.com/mun-lang/mun"
license = "MIT OR Apache-2.0"
keywords = ["game", "hot-reloading", "language", "mun", "scripting"]
categories = ["game-development", "mun"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lsp-types = "0.74"
log = "0.4"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
async-std = { version = "1.8.0", features=["attributes"] }
futures = "0.3"
anyhow = "1.0"
thiserror = "1.0"
ra_vfs = "0.6.1"
salsa = "0.15.0"
hir = { version = "=0.2.0", path="../mun_hir", package="mun_hir" }
rayon = "1.3"
num_cpus = "1.13.0"
mun_target = { version = "=0.2.0", path = "../mun_target" }
mun_syntax = { version = "=0.2.0", path = "../mun_syntax" }
mun_diagnostics = { version = "=0.1.0", path = "../mun_diagnostics" }

[dev-dependencies]
mun_test = { path = "../mun_test"}
tempdir = "0.3.7"
insta = "0.16"
