[package]
name = "mun_codegen"
version = "0.3.0"
authors = ["The Mun Team <team@mun-lang.org>"]
edition = "2021"
description = "LLVM IR code generation for Mun"
documentation = "https://docs.mun-lang.org/v0.3"
readme = "README.md"
homepage = "https://mun-lang.org"
repository = "https://github.com/mun-lang/mun"
license = "MIT OR Apache-2.0"
keywords = ["game", "hot-reloading", "language", "mun", "scripting"]
categories = ["Game development", "Mun"]

[dependencies]
rustc-hash = "1.1.0"
mun_abi = { version = "=0.4.0-dev", path = "../mun_abi" }
bytemuck = "1.4.1"
mun_hir = { version = "=0.4.0-dev", path = "../mun_hir" }
itertools = "0.10.3"
mun_codegen_macros = { version = "=0.4.0-dev", path = "../mun_codegen_macros" }
mun_target = { version = "=0.4.0-dev", path = "../mun_target" }
lld_rs = "120.0.1"
anyhow = "1.0.31"
thiserror = "1.0.19"
salsa = "0.16.1"
array-init="2.0.0"
tempfile = "3"
paste = "1.0.7"
parking_lot = "0.12.0"
inkwell = { version = "=0.1.0-beta.4", features = ["llvm12-0", "no-libffi-linking"]}
by_address = "1.0.4"
mun_paths = { version= "=0.4.0-dev", path="../mun_paths"}
smallvec = { version = "1.6.1", features=["union"] }
once_cell = "1.4.0"

[dev-dependencies]
mun_abi = { path = "../mun_abi", package = "mun_abi", features=["serde"] }
insta = { version="1.12.0", features = ["ron"]}
mun_libloader = { path = "../mun_libloader" }
mun_test = { path = "../mun_test" }
mun_runtime = { path = "../mun_runtime" }
