parameters:
  rust_version: stable

jobs:
  - job: ${{ parameters.name }}
    displayName: Check rustfmt
    pool:
      vmImage: ubuntu-16.04
    steps:
    - checkout: self
      submodules: true
    - template: azure-install-rust.yml
      parameters:
        rust_version: ${{ parameters.rust }}
    - script: |
        rustup component add rustfmt
        cargo fmt --version
      displayName: Install rustfmt
    - script: |
        cargo fmt --all -- --check
      displayName: Check formatting