parameters:
  rust: stable

jobs:
- job: ${{ parameters.name }}
  displayName: tarpaulin
  pool:
    vmImage: ubuntu-18.04

  steps:
  - checkout: self
    submodules: true

  - template: azure-install-rust.yml
    parameters: 
      rust: ${{ parameters.rust }}

  - template: azure-install-llvm.yml

  - script: |
      cargo install cargo-kcov
      sudo apt-get install cmake g++ pkg-config jq
      sudo apt-get install libcurl4-openssl-dev libelf-dev libdw-dev binutils-dev libiberty-dev
      cargo kcov --print-install-kcov-sh | sh      
    displayName: "Install kcov"

  - script: cargo kcov --all
    displayName: Run kcov

  - script: bash <(curl -s https://codecov.io/bash)
    displayName: Upload results to codecov
    env:
      CODECOV_TOKEN: ${{ parameters.codecov_token }}